version: '3'

services:
  
  app:
    restart: always
    build:
      context: .
    ports: 
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py initadmin &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
      - DEBUG=False
      - SECRET_KEY=django-insecure-0)0_n^-wx5@k3t6k#al2#*=8q$$*&8oq%9f@kw!lu_88!d_e908
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@test.com
      - DJANGO_SUPERUSER_PASSWORD=admin

  db:
    image: postgres:10-alpine
    volumes:
      - ./db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
